### ISSUE TITLE
Check if growth stage = 0 for harvest

### ISSUE THREAD

**Issue by amos1814** [borrascador/rain#146]

**Comment by borrascador** [comment]
1. Should I throw an error if the test fails?
2. If yes, which error? Maybe we should either adjust the messages we have or make a new one.

**Comment by amos1814** [comment]
I send an update when it reaches growth stage =0. I think you should make it impossible to harvest until you get this update. Maybe have a less opaque image of that crop in the harvest menu. And I'll send an error if you somehow manage to send a harvest message before growth stage=0.

**Comment by borrascador** [comment]
I do have the crop progress images, I can use those and make them non-interactive when not ripe. Otherwise I could make it so that harvest is only an option when a ripe crop is present and only ripe crops are displayed.

**Comment by amos1814** [comment]
Yes non-interactive thats the solution
