### ISSUE TITLE
Hunting Overhaul

### ISSUE THREAD

**Issue by borrascador** [borrascador/rain#239]
* Toggle hunting mode with UI element
* Moving is allowed while hunting
* For now, you can only encounter animals in hunting mode
* Keep individual hunting encounters as they are right now
* But only one animal at a time, get rid of chain as it is now
* `start_hunt` and `stop_hunt` messages signal toggle state
* Potential errors: `stop_hunt` if not hunting and vice versa
* Keep the "continue hunting?" question at the end of each encounter

**Comment by borrascador** [comment]
Before I get too far into this, it seems that when I sent `start_hunt` it might make sense for you to send `hunting: true` as a response, and send `hunting: false` after I send `stop_hunt`. What do you think?

**Comment by amos1814** [comment]
I agree

**Comment by borrascador** [comment]
By the way `hunting: bool` should always be in login_response

**Comment by borrascador** [comment]
* No animal encounters when standing still
* Less frequent animal encounters: 
* When not hunting, only aggressive animals will attack you, and even so rarely
* When hunting, you can encounter any animal, but encounters will still be sporadic / uncommon
* Remove 'keep hunting' screen
* Try to remove simultaneous animal encounters

**Comment by borrascador** [comment]
Last Round of Todos

* Allow pace 0, 1, and 2 while hunting, with different effects
* No animal encounters when standing still
* Add client errors
* Server errors too?
