### ISSUE TITLE
Handle move requests and position updates

### ISSUE THREAD

**Issue by borrascador** [borrascador/rain#283]
Handle receiving a newly changed move request with the following fields: 

```
{
      id: int, // party member id
      xCoord: int,
      yCoord: int,
      xPos: int,
      yPos: int,
      pace: int,
}
```

Send update messages with new party member position data to client at a 0.1 second movement tick resolution.

**Comment by amos1814** [comment]
{
  type: EVENT_REQUEST,
  payload: {
    eventType: move,
    payload: {
      id: int,
      positionTarget: int,
      xTarget: int,
      yTarget: int,
      pace: int/float?,
    }
  }
}

{
  type: UPDATE,
  payload: {
    party: [
      {id:int,  position: int,  x: int,  y:int,  moving(optional): boolean},
      ...
    ]
  }
}

The "moving" field in update might be useful in case we want to show or gray out certain options client side, depending on whether the members are moving.

Estimate: 2-5 hours

**Comment by amos1814** [comment]
`{
  type: EVENT_REQUEST,
  payload: {
    eventType: move,
    payload: {
      id: int,
      positionTarget: int,
      xTarget: int,
      yTarget: int,
      pace: int/float?,
    }
  }
}

{
  type: UPDATE,
  payload: {
    party: [
      {id:int,  position: int,  x: int,  y:int,  moving(optional): boolean},
      ...
    ]
  }
}`

**Comment by amos1814** [comment]
[move.txt](https://github.com/borrascador/rain/files/3304013/move.txt)

**Comment by borrascador** [comment]
This is a good start. Might need to send tile data eventually when we implement fog of war again. Might also be helpful to send an indication of how fast the player is moving? Maybe send a value for how long it will take to get to the next tile. Also not sure how we will handle choosing a specific path for the player to travel from point A to B, and how to communicate that between client and server.

**Comment by amos1814** [comment]
[move.txt](https://github.com/borrascador/rain/files/3366218/move.txt)

**Comment by amos1814** [comment]
Movement tick length: 0.1s

Member speed: 1-50 (50 is slowest)

Member speed is determined by terrain, weight carried, movement type, pace, etc.

It is equal to the number of ticks before the member moves 1 tile. The fastest speed is then 10 tiles per second. The slowest speed is 1 tile every 5 seconds.
