### ISSUE TITLE
Client-side Reconciliation of Server-side Actions

### ISSUE THREAD

**Issue by borrascador** [borrascador/rain#29]
TO-DO:
* [x] Add REQUEST actions
* [x] Make reducers for REQUEST actions
* [x] Make reducers for RECEIVE actions
* [x] Activate alphabetical text keys
* [x] Update list of tiles instead of replacing it

**Comment by borrascador** [comment]
This is a good place to discuss how we will format actions and their types. For example, instead of message_type, the type should simply be called 'type', and all other data should be included inside of a payload. For example: 

`public void sendRegister(String name, String playerClass){
	JSONObject jo = new JSONObject();
	JSONObject payload = new JSONObject();
	
	payload.accumulate("name", name);
	payload.accumulate("player_class", playerClass);
	
	jo.accumulate("type", "register");
	jo.accumulate("payload", payload);
	
	send(jo.toString());
}`

**Comment by borrascador** [comment]
This is a good place to talk about what actions should look like. I found a library that translates websocket messages directly into redux actions and vice versa, so we should follow the [Flux Standard Action ](https://github.com/redux-utilities/flux-standard-action) (FSA) pattern in all client-server communications. So in the Client class, the code for sending a register message should look more like this:


	public void sendRegister(String name, String playerClass){
	    JSONObject jo = new JSONObject();
	    JSONObject payload = new JSONObject();
		
	    payload.accumulate("name", name);
	    payload.accumulate("player_class", playerClass);
		
	    jo.accumulate("type", "register");
	    jo.accumulate("payload", payload);
		
	    send(jo.toString());
	}

And in the MessageHandler class, the code for receiving the message should be more like this:

	String type = jo.getString("type");
	JSONObject payload = jo.getJSONObject("payload");
	switch (type) {
		case "register":
			World.addPlayer(payload.getString("name"), payload.getString("player_class"));
			break;
	}

We also still need to agree on a naming convention for our actions. I like all caps, and always knowing who sent what. Maybe for now we can go with FOO_REQUEST on the client side and FOO_RESPONSE on the server side to make things simple. So POSITION_REQUEST and POSITION_RESPONSE, as well as REGISTER_REQUEST and REGISTER_RESPONSE.

What do you think?

**Comment by amos1814** [comment]
I'll change it from "message_type" to "type"

So for now we will have

REGISTER_REQUEST
REGISTER_RESPONSE
POSITION_REQUEST
POSITION_RESPONSE

And if POSITION_REQUEST contains a tile argument then it will be a move

**Comment by borrascador** [comment]
Sounds good, thanks.

It's probably a good idea to distinguish between clients that have open websocket connections to the server (connected), accounts that are currently logged in (online), and all registered accounts (registered). I'm considering adding in a simple sign-in screen that is shown after the websocket is opened but before the user identifies herself to the server.

By the way, it would be nice to have a spec document to keep track of what each client/server action is meant to look like, so we can document existing actions and design upcoming actions.
