### ISSUE TITLE
What's the best way to host server for now?

### ISSUE THREAD

**Issue by borrascador** [borrascador/rain#297]
Learn how to get us to a state where we can login to the same instance and play by any means necessary. No hold barred. Except the full nelson. That is the most dangerous hold.

Leave links/findings in comments.

**Comment by borrascador** [comment]
Dan says he's paying for Amazon. Let's see if this works???

**Comment by amos1814** [comment]
I logged on to Amazon today, still trying to figure out how to run the server application (Do I need to export everything as a .jar file). 

Estimate: another 1-3 hours

**Comment by borrascador** [comment]
Since #301 is done, you are now able to click on the "CONNECTED/DISCONNECTED" line in the title screen and select a server endpoint url. Should make this a lot easier! :+1:

**Comment by amos1814** [comment]
1. Go to Amazon Web Services and login using credentials I'll pm you. Go to "instances". You should see Dan's Server and Jan's server.

2. I think you should have have a key pair file KP2.pem somewhere on your computer from before. Go to the directory containing it

ssh -i KP2.pem ec2-user@18.221.158.0

3. Make sure you have java and git installed. Pull or clone the project

4. Go to /home/ec2-user/rain/src/server/rainserver

java -jar server.jar
