### ISSUE TITLE
Update player and party data structures

### ISSUE THREAD

**Issue by borrascador** [borrascador/rain#299]
- Define player and party data structures in light of redefining party as a grouping of players or NPCs.
- Each player will be attached to one party member.
- Add fields to distinguish current player from other player from NPC. And for NPCs, who controls that NPC.
- Make sure players receive updates when other players move.

Question: how to store data about other players on map?
Answer: store it in their respective tiles.

Leave ideas in comments. Will probably implement server before client.

**Comment by amos1814** [comment]
**Added new fields to player:**

character: int
party: int

**Created new class "Party"**

Members: ArrayList<Integer>
Name: String
Later we can add things like references to shared inventory

**Added field to World.java**
HashMap<Integer, Party> parties;

Added to Member npc: boolean 

Now I need to change all the methods that involve looking up party members

Estimate: 1-2 more hours

**Comment by borrascador** [comment]
Could you open a PR for this without merging it in? That way I'll be able to work on the client-side changes in a branch and merge into master when both sides work together.

**Comment by borrascador** [comment]
How are we going to handle players from other parties and NPCs such as animals? Would it make sense to change the `party` array into a `characters` array and do everything from there? There could be an extra field for party id which could be null for a character that doesn't belong to a party, such as an animal NPC. Either way a `characters` array would be most extensible. Might also be nice to send a separate value to the client with current party id if we go this way.

**Comment by amos1814** [comment]
I think we should have both the `party` array and a `characters` array since there will probably be fields unique to your own party. We could also have a separate array for animals and stationary npcs. To me that would be easier than having a universal array with many different optional fields.

**Comment by borrascador** [comment]
I think you're right, actually. I didn't think enough about those cases. Handling the universal array doesn't sound very fun.

**Comment by borrascador** [comment]
I will close this after checking in UI changes to show more information about party members including `self`, `npc`, and currently selected player.

**Comment by borrascador** [comment]
Split all game entities/characters into `party`, `players`, and `npcs`.
