### ISSUE TITLE
Chat window

### ISSUE THREAD

**Issue by borrascador** [borrascador/rain#313]
In order to facilitate single-party multiplayer play, there should be a in-game chat capability that allows some form of in-party and out-of-party communication. On the front-end this requires an HTML element with chat capability that would hover over the bottom of the screen and a connection to the chat server instance. The chat element would:

* Let users compose, send, and view messages sent to a global namespace
* Identify sender for each message that is received

Future features (still need to create story):
* Add timestamp to each message
* Toggle between broadcasting message to party or to global instance
* Display in-party and global chat messages in different ways
* Investigate standing up separate server instance for chat, possibly IRC

**Comment by borrascador** [comment]
Create a new top-level property returned by the UPDATE message that is called `messages` and is an array of new messages sent over chat. 

Data structure:

**Comment by borrascador** [comment]
Just made a new commit that implements the chat window in 7871016 -- it was pretty easy actually. The server barfs an error for invalid message type for now, but once you implement on the backend the chat window should show live server updates.

**Comment by amos1814** [comment]
Do we want to use `messages []` to give notifications such as: 
_Your party member **a** has logged out_
_Your party members are hungry_
?

In that case the server could send those messages without a `user:`

**Comment by borrascador** [comment]
I think that's a good idea. The client probably won't break if you do it that way currently, and I can add in some code that formats those messages differently (probably a different color)

**Comment by borrascador** [comment]
Come to think of it, the client could take the errors it receives now and add it to the same list. Maybe render those red. What do you think of adding a `type` field? Might be ``
