### ISSUE TITLE
Switch server map source from tiles.json to map.json

### ISSUE THREAD

**Issue by borrascador** [borrascador/rain#79]
`tiles.json` is the result of a rather arbitrary parsing of `map.json`, which is the raw output from Tiled, our tile map editor. This is the current conversion code in JavaScript:
```
function buildMap(map) {
  let mapArray = [];
  for (let y = 0; y < map.height; y++) {
    for (let x = 0; x < map.width; x++) {
      let id = y * map.width + x;
      mapArray[id] = { id, x, y, layers: {
        base: 0,
        middle: map.layers[1].data[id] === 0 ? 0 : map.layers[1].data[id] - 1
      }};
    }
  }
  return mapArray;
}
```

Since events will most likely be tied to tile data, the server-side conversion will also have to incorporate this additional information in the conversion step. Format TBD

**Comment by amos1814** [comment]
visible layers are stored in Tile.layers, invisible layers are stored in Tile.events
